### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nelsonjchen** [joshcomley/EfCore.NestedSets#1]
Could a license be added to the code in this repository?

https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by joshcomley** [comment]
Sure, but actually I'm no good with licenses! Which one means, essentially,
free for anything?

Additionally, I have better nested set code that works with EF Core
SPECIFICALLY and only with SQL as the database provider, if you'd prefer
that I could publish it.

Kind regards,
Josh

**Comment by nelsonjchen** [comment]
Free for anything would let anybody rip off your name and not provide attribution. That's not cool. So we want some protection at least. That said, [I think choosing the MIT License like as used in .NET Core would be the one in your interest](https://choosealicense.com).

I'm interested in using this with PostgreSQL so an SQL Server-only version wouldn't interest me that much.

**Comment by nelsonjchen** [comment]
https://github.com/dotnet/corefx/blob/master/LICENSE.TXT

.NET Core didn't even bother with the year. So it can be even lower maintenance.

**Comment by nelsonjchen** [comment]
Actually, I am interested in the SQL server version. It wouldn't happen to be using `hierarchyid` would it which is making it SQL Server only? I would be interested in using it as a reference for a PostgreSQL using `ltree` or adding `ltree` support to it. 

I'm looking at moving some model from using a Rails nested sets to ASP.NET Core nested sets then eventually to `ltree`.
